{"uuid": "7ecf227b-cd8a-4de7-8457-2fb9311ce0ef", "children": ["f125e9d8-63a3-4c6a-8630-83808c5dca5f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: Browsing context has been discarded\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:187:5\nNoSuchWindowError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:613:5\nassert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:485:13\nassert.open@chrome://remote/content/shared/webdriver/Assert.sys.mjs:147:4\nGeckoDriver.prototype.maximizeWindow@chrome://remote/content/marionette/driver.sys.mjs:2626:15\ndespatch@chrome://remote/content/marionette/server.sys.mjs:320:40\nexecute@chrome://remote/content/marionette/server.sys.mjs:291:16\nonPacket/<@chrome://remote/content/marionette/server.sys.mjs:264:20\nonPacket@chrome://remote/content/marionette/server.sys.mjs:265:9\n_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:496:20\n\n", "trace": "  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ramadhma\\PycharmProjects\\Assessment\\TestAssessment\\tests\\conftest.py\", line 69, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 498, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1695386825541, "stop": 1695386846758}], "start": 1695386825541, "stop": 1695386848299}