{"uuid": "4c25e29b-0425-4208-b270-3d02d96ec7f4", "children": ["cc585c63-8fb8-4cb7-8efd-4903b4164b76"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 117.0.5938.89 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00E2A813+48355]\n\t(No symbol) [0x00DBC4B1]\n\t(No symbol) [0x00CC5358]\n\t(No symbol) [0x00CE61AC]\n\t(No symbol) [0x00CE1EF3]\n\t(No symbol) [0x00CE0579]\n\t(No symbol) [0x00D10C55]\n\t(No symbol) [0x00D1093C]\n\t(No symbol) [0x00D0A536]\n\t(No symbol) [0x00CE82DC]\n\t(No symbol) [0x00CE93DD]\n\tGetHandleVerifier [0x0108AABD+2539405]\n\tGetHandleVerifier [0x010CA78F+2800735]\n\tGetHandleVerifier [0x010C456C+2775612]\n\tGetHandleVerifier [0x00EB51E0+616112]\n\t(No symbol) [0x00DC5F8C]\n\t(No symbol) [0x00DC2328]\n\t(No symbol) [0x00DC240B]\n\t(No symbol) [0x00DB4FF7]\n\tBaseThreadInitThunk [0x7780FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77E37B1E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77E37AEE+238]\n\n", "trace": "  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ramadhma\\PycharmProjects\\Assessment\\TestAssessment\\tests\\conftest.py\", line 55, in setup\n    driver = webdriver.Chrome(service=ser_obj, options=options)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 54, in __init__\n    super().__init__(\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 291, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\ramadhma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1695142900018, "stop": 1695142912111}], "start": 1695142900018, "stop": 1695142912415}